# -*- coding: utf-8 -*-
"""Clase 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13dCtmXSXJLShOY9ztqhpPYb7G47J-oa-

# CLASE 2: IMPORTACION DE BIBLIOTECAS Y FUNDAMENTOS DE NUMPY

## Instalación de paquetes
"""

!pip install matplotlib

# Listado de paquetes
!pip list

"""## Importación de paquetes"""

# Forma 1
import matplotlib

matplotlib.pyplot.plot([1, 2, 4, 6], [3, 2, 1, 5])

import numpy

numpy.pi

# Forma 2
import matplotlib.pyplot as plt

x1 = [1, 2, 3, 1]
x2 = [3, 4, 3, 3]

plt.plot(x1, x2)
plt.plot([1.5, 2.5, 2, 1.5], [3.5, 3.5, 3, 3.5])
plt.xlabel("Eje X")

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Forma 3
from matplotlib.pyplot import plot as p

p(x1, x2)

# Forma 3
from sklearn.preprocessing import StandardScaler as scaler

# Forma 4
from sklearn.preprocessing import *

"""## NUMPY"""

import numpy as np

"""### ARRAY 1D"""

# ARRAY 1D
expr = np.array([0.5, 1.32, 4.1, -2.3, -0.6, 0.2, 1])

print(expr)

expr * 2

expr + 2

# INDEXADO
print(expr[0])

print(expr[-1])

print(expr[1:4])

print(expr[1:])

# Extra
#np.int(expr[-1])

# Dimensiones
print(expr.ndim)

# Forma
print(expr.shape)

# Normalizar (min-max): 0 - 1

# (X - Xmin) / (Xmax - Xmin)

(expr - expr.min()) / (expr.max() - expr.min())

"""### ARRAY 2D"""

# ARRAY 2D
#               Edad, Altura, Glucosa
data = np.array([[18, 1.67, 120],
                 [25, 1.76, 130],
                 [52, 1.55, 86],
                 [78, 1.7, 140]])

print(data)

data * 3

data.ndim

# Indexado

print(data[0, 0])

print(data[3, 2])

print(data[3, :]) # Llamar fila

print(data[:, 1]) # Llamar columna

print(data[1:3, 1:3])

data.shape

# Trasponer
dataT = data.T
dataT

dataT.shape

A = np.array([1, 2, 3, 4]) # 1D
A2 = np.array([[1], [2], [3], [4]]) # 2D

print(A2.shape)

print(data + data)
print(data - data)
print(data * data) # No es una multiplicación matricial

print(np.dot(data, dataT))

# 2x2 X 2x2 sí
# 4x2 X 4x2 No

# 4x3 X 3x4 Sí

##
#               Peso, Altura, Glucosa
data = np.array([[81, 1.67, 120],
                 [52, 1.76, 130],
                 [62, 1.55, 86],
                 [78, 1.7, 140]])

data[:, 0] / (data[:, 1]**2)

"""### ARRAY 3D"""

data3d = np.array([
    [
        [0.5, 0.2, 0.3, 0.2],
        [0.4, 0.5, 0.7, 0.2],
    ],
    [
        [0.2, 0.2, 0.3, 0.1],
        [0.3, 0.5, 0.7, 0.1],
    ],
    [
        [0.5, 0.1, 0.3, 0.2],
        [0.2, 0.5, 0.8, 0.0],
    ]
])

print(data3d)

data3d.shape

data3d[0, 1, 2] = 0

data3d

data3d[1, :, :] = [[0, 0, 0, 0], [0, 0, 0, 0]]

data3d

"""## FUNCIONES EN NUMPY"""

# Constantes Numpy
print(np.e)
print(np.pi)
print(np.nan)

# Operadores Numpy
print(np.exp(data)) # Exponencial
print(np.log(10)) # Logaritmo natural
print(np.log10(100)) # Logaritmo 10
print(np.sqrt(data)) # Raiz cuadrada

# ARANGE

print(np.arange(100)) # fin = 100

print(np.arange(10, 21)) # inicio = 10, fin = 21

print(np.arange(1, 100, 3)) # inicio = 1, fin = 100, paso = 3

ADN = "CGTACGATCGATCGACTC"

for n in np.arange(0, len(ADN), 3): # 0, 3, 6, 9, ..., 15
  print(ADN[n:n+3])

### LINSPACE

print(np.linspace(0, 10, 101)) # inicio = 1, fin = 10 (I), Cantidad = 10

# Modelos del crecimiento bacteriano

N0 = 10 # Población inicial
r = 0.5 # Tasa de crecimiento
K = 10000 # Capacidad de carga

t = np.linspace(1, 30, 1000) # Serie de tiempo
N = K / (1 + ((K - N0) / N0) * np.exp(-r*t)) # Función logística

plt.plot(t, N)

# MESHGRID

x = np.linspace(-5, 5, 11)
y = np.linspace(-5, 5, 11)

# X =       -5,   -4, -3, ...
# Y = -5 (-5, -5), (-5, -4)
#.    -4 (-4, -5)
#.    -3

_x, _y = np.meshgrid(x, y)

plt.plot(_x, _y, "o")

x = np.linspace(-5, 5, 11)
y = np.linspace(-5, 5, 11)

_x, _y = np.meshgrid(x, y)

z = -np.sqrt(_x**2 + _y**2)

plt.matshow(z)

from mpl_toolkits.mplot3d import Axes3D

x = np.linspace(-5, 5, 1000)
y = np.linspace(-5, 5, 1000)

_x, _y = np.meshgrid(x, y)

z = -np.sqrt(_x**2 + _y**2)

fig = plt.figure()

ax = fig.add_subplot(111, projection = "3d")

ax.plot_surface(_x, _y, z, cmap = "viridis")

plt.show()

### NUMEROS ALEATORIOS
rng = np.random.default_rng()
rng

# entre 0 y 1
print(rng.random(5))
print(rng.random((5, 6)))

# Enteros
print(rng.integers(1, 10, size = 5))
print(rng.integers(1, 10, size = (5, 4)))

# Normales
print(rng.normal(0, 1, 100))
print(rng.normal(10, 10, 100))

#.             media, sd
datos = rng.normal(0, 1, 10000)
plt.hist(datos, bins = 30)
plt.show()

###
datos = np.array([1.1, 4.2, 2.1, 5.3, 3.1, 4.3, 2.2, 4.1, 2.2, 3.1, 1.1, 3.4,
                  1.2, 4.1, 2.3, 5.1, 3.0, 4.1, 2.0, 4.3, 2.1, 3.8, 1.9, 3.7,
                  2.2, 3.1, 4.3, 5.6, 3.7, 4.8, 2.1, 4.7, 2.8, 3.9, 1.7, 3.5, 4 ,
                  2.6, 3.7, 4.8, 5.9, 3.3, 4.1, 2.7, 4.6, 2.5, 3.2, 1.3, 3.5,
                  2.6, 4.7, 2.4, 5.7, 3.5, 2.7, 4.8, 2.6, 3.8, 1, 3, 2, 3, 4])

plt.hist(datos, bins = 20)

m = datos.mean()
sd = datos.std()

plt.hist(rng.normal(m, sd, 100), bins = 50, alpha = 0.5)

sexo = ["M", "F", "F", "M", "F", "M", "M", "M", "F", "F"]
rng.choice(sexo, 3)